version: v1
services:
  endpoint-monitor:
    build: .
    volumes:
      - ./:/go/src/github.com/patdaman/endpoint-monitor
    environment:
      - BUILDKITE_AGENT_ACCESS_TOKEN
      - BUILDKITE_JOB_ID
      - BUILDKITE_BUILD_ID
      - BUILDKITE_BUILD_NUMBER
      